name: Build Publish Layers
on:
  release:
    types: [published]

jobs:
    publish-python37:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '_python')
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.7"
            - name: Run tests
              run: |
                pip install -U awscli
            - name: Publish layer
              run: |
                cd python
                ./publish-layers.sh python3.7
    
    publish-python38:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '_python')
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.8"
            - name: Run tests
              run: |
                pip install -U awscli
            - name: Publish layer
              run: |
                cd python
                ./publish-layers.sh python3.8
