name: Publish Java Layers

on:
  push:
    tags:
      - v**_java

jobs:
  publish-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ java8al2, java11, java17, java21 ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java version
        id: set-java-version
        run: |
          declare -A java_version_map
          java_version_map=(
            ["java8al2"]="8"
            ["java11"]="11"
            ["java17"]="17"
            ["java21"]="21"
          )
          numeric_version=${java_version_map[${{ matrix.java-version }}]}
          echo "JAVA_NUMERIC_VERSION=$numeric_version" >> $GITHUB_ENV

      - name: Use Java ${{ env.JAVA_NUMERIC_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ env.JAVA_NUMERIC_VERSION }}
      - name: Check Tag
        id: java-check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+(\.[0-9]+)*_java$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Publish ${{ matrix.java-version }} layer
        if: steps.java-check-tag.outputs.match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make publish-${{ matrix.java-version }}-ci
      - name: Publish ECR image for ${{ matrix.java-version }}
        if: steps.java-check-tag.outputs.match == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd java
          ./publish-ecr-images.sh build-publish-${{ matrix.java-version }}-ecr-image
